import { FormEvent,useEffect,useRef,useState } from 'react';
import { api } from '../lib/api';
import { MessageRecord } from '../lib/types';
import { Empty,ErrorNotice,PageHeader } from '../components/Common';

export function MessagesPage({clusterId}:{clusterId:string}){
 const[items,setItems]=useState<MessageRecord[]>([]),[selected,setSelected]=useState<MessageRecord>(),[error,setError]=useState(''),[loading,setLoading]=useState(false),[producer,setProducer]=useState(false),[live,setLive]=useState(false);
 const[topic,setTopic]=useState(''),[partition,setPartition]=useState(-1),[mode,setMode]=useState('latest'),[offset,setOffset]=useState(0),[timestamp,setTimestamp]=useState('');const stream=useRef<EventSource|null>(null);
 const stop=()=>{stream.current?.close();stream.current=null;setLive(false)};
 useEffect(()=>stop,[clusterId]);useEffect(()=>()=>stream.current?.close(),[]);
 async function search(e:FormEvent<HTMLFormElement>){e.preventDefault();stop();setLoading(true);try{const q=new URLSearchParams({topic,partition:String(partition),mode,limit:String(new FormData(e.currentTarget).get('limit')),offset:String(offset),timestamp:String(timestamp?new Date(timestamp).getTime():0)});const result=await api.get<{items:MessageRecord[]}>(`/api/v1/clusters/${clusterId}/messages?${q}`);setItems(result.items);setError('')}catch(reason){setError(reason instanceof Error?reason.message:'查询失败')}finally{setLoading(false)}}
 function follow(){if(live){stop();return}if(!topic.trim()){setError('请先输入 Topic');return}setItems([]);setSelected(undefined);setError('');const q=new URLSearchParams({topic,partition:String(partition)});const source=new EventSource(`/api/v1/clusters/${clusterId}/messages/stream?${q}`);stream.current=source;source.onmessage=e=>{const record=JSON.parse(e.data) as MessageRecord;setItems(current=>[record,...current].slice(0,500))};source.onerror=()=>{setError('实时连接已中断，可重新开始跟随');stop()};setLive(true)}
 return <><PageHeader code="03 / MESSAGES" title="消息检索器" description="有界读取或实时跟随 Kafka 原始消息；支持 JSON、Headers、Offset 与时间定位。" actions={<button className="button primary" onClick={()=>setProducer(!producer)}>↑ 生产消息</button>}/><form className="query-bar" onSubmit={search}><label>TOPIC<input required placeholder="输入 Topic 名称" value={topic} onChange={e=>setTopic(e.target.value)}/></label><label>PARTITION<input type="number" min="-1" value={partition} onChange={e=>setPartition(Number(e.target.value))}/></label><label>START<select value={mode} onChange={e=>setMode(e.target.value)}><option value="latest">最近消息</option><option value="earliest">最早消息</option><option value="offset">指定 Offset</option><option value="timestamp">指定时间</option></select></label>{mode==='offset'?<label>OFFSET<input type="number" min="0" value={offset} onChange={e=>setOffset(Number(e.target.value))}/></label>:mode==='timestamp'?<label>TIME<input type="datetime-local" required value={timestamp} onChange={e=>setTimestamp(e.target.value)}/></label>:<label>LIMIT<input name="limit" type="number" min="1" max="500" defaultValue="100"/></label>}<input name="limit" type="hidden" value="100"/><button className="button primary" disabled={loading}>{loading?'读取中…':'开始查询 →'}</button><button type="button" className={`button ${live?'danger':'ghost'}`} onClick={follow}>{live?'■ 停止跟随':'● 实时跟随'}</button></form>{live&&<div className="live-strip"><span/>LIVE · 仅保留最近 500 条消息</div>}{error&&<ErrorNotice message={error}/>} {producer&&<Producer clusterId={clusterId} done={()=>setProducer(false)}/>}<div className="message-layout"><div className="message-list">{items.length===0?<Empty title={live?'等待新消息':'等待查询'} detail={live?'实时连接已建立，正在监听新记录。':'选择 Topic 与起始位置后读取消息。'}/>:items.map(record=><button key={`${record.partition}-${record.offset}`} className={selected===record?'active':''} onClick={()=>setSelected(record)}><span>P{record.partition}</span><b>@{record.offset}</b><time>{new Date(record.timestamp).toLocaleString()}</time><code>{record.key||'∅ key'}</code></button>)}</div><div className="message-detail">{selected?<><header><span>P{selected.partition} · OFFSET {selected.offset}</span><b>{new Date(selected.timestamp).toLocaleString()}</b></header><h4>KEY</h4><pre>{selected.key||'null'}</pre><h4>VALUE</h4><pre>{pretty(selected.value)}</pre><h4>HEADERS</h4><pre>{JSON.stringify(selected.headers||[],null,2)}</pre></>:<div className="detail-placeholder">选择一条消息查看完整内容</div>}</div></div></>;
}
function pretty(value:string){try{return JSON.stringify(JSON.parse(value),null,2)}catch{return value}}
function Producer({clusterId,done}:{clusterId:string;done:()=>void}){const[error,setError]=useState('');async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);try{await api.post(`/api/v1/clusters/${clusterId}/messages`,{topic:d.get('topic'),partition:Number(d.get('partition')),key:d.get('key'),value:d.get('value'),headers:[]});done()}catch(reason){setError(reason instanceof Error?reason.message:'发送失败')}}return <form className="producer" onSubmit={submit}><div><b>PRODUCE RECORD</b><span>消息正文不会写入审计日志</span></div><input name="topic" required placeholder="Topic"/><input name="partition" type="number" defaultValue="-1"/><input name="key" placeholder="Key（可选）"/><textarea name="value" required placeholder='{"hello":"kafka"}'/><button className="button primary">发送</button>{error&&<ErrorNotice message={error}/>}</form>}
