import { useEffect, useState } from 'react';
import { ErrorNotice, Loading, PageHeader } from '../components/Common';
import { api } from '../lib/api';
import { AppConfig, ConfigBackup, KafkaClusterConfig } from '../lib/types';

const blank=():KafkaClusterConfig=>({id:'',name:'',brokers:[''],security:{protocol:'PLAINTEXT'}});

export function SettingsPage({onSaved}:{onSaved:()=>void}){
 const[cfg,setCfg]=useState<AppConfig>();const[backups,setBackups]=useState<ConfigBackup[]>([]);const[error,setError]=useState('');const[saving,setSaving]=useState(false);
 const load=()=>{api.get<AppConfig>('/api/v1/config').then(setCfg).catch(e=>setError(e.message));api.get<{items:ConfigBackup[]}>('/api/v1/config/backups').then(r=>setBackups(r.items)).catch(()=>{})};useEffect(load,[]);
 if(!cfg)return <><PageHeader code="05 / CONFIG" title="集群配置" description="配置写入 YAML，并在连接验证成功后热加载。"/>{error?<ErrorNotice message={error}/>:<Loading/>}</>;
 const update=(index:number,patch:Partial<KafkaClusterConfig>)=>setCfg({...cfg,clusters:cfg.clusters.map((item,i)=>i===index?{...item,...patch}:item)});
 async function save(){setSaving(true);try{await api.put('/api/v1/config',cfg);setError('');onSaved();load()}catch(reason){setError(reason instanceof Error?reason.message:'保存失败')}finally{setSaving(false)}}
 async function restore(id:string){if(!confirm(`确认回滚配置到 ${id}？`))return;try{await api.post(`/api/v1/config/backups/${id}`,{});load();onSaved()}catch(reason){setError(reason instanceof Error?reason.message:'回滚失败')}}
 return <><PageHeader code="05 / CONFIG" title="集群配置" description="保存前会连接所有 Broker；失败时保留当前有效配置和客户端。" actions={<button className="button primary" disabled={saving} onClick={save}>{saving?'验证连接中…':'保存并热加载'}</button>}/>{error&&<ErrorNotice message={error}/>}<div className="settings-grid">{cfg.clusters.map((cluster,index)=><article className="config-card" key={`${cluster.id}-${index}`}><header><span>CLUSTER {String(index+1).padStart(2,'0')}</span><button onClick={()=>setCfg({...cfg,clusters:cfg.clusters.filter((_,i)=>i!==index)})}>移除</button></header><label>显示名称<input value={cluster.name} onChange={e=>update(index,{name:e.target.value})}/></label><label>唯一 ID<input value={cluster.id} onChange={e=>update(index,{id:e.target.value})}/></label><label>Broker 地址（每行一个）<textarea value={cluster.brokers.join('\n')} onChange={e=>update(index,{brokers:e.target.value.split('\n').filter(Boolean)})}/></label><label>连接协议<select value={cluster.security.protocol||'PLAINTEXT'} onChange={e=>update(index,{security:{...cluster.security,protocol:e.target.value}})}><option>PLAINTEXT</option><option>SSL</option><option>SASL_PLAINTEXT</option><option>SASL_SSL</option></select></label>{cluster.security.protocol.startsWith('SASL')&&<><label>认证机制<select value={cluster.security.mechanism||'SCRAM-SHA-256'} onChange={e=>update(index,{security:{...cluster.security,mechanism:e.target.value}})}><option>PLAIN</option><option>SCRAM-SHA-256</option><option>SCRAM-SHA-512</option></select></label><label>用户名<input value={cluster.security.username||''} onChange={e=>update(index,{security:{...cluster.security,username:e.target.value}})}/></label><label>密码<input type="password" placeholder="留空保持原密码" onChange={e=>update(index,{security:{...cluster.security,password:e.target.value}})}/></label></>}</article>)}<button className="add-cluster" onClick={()=>setCfg({...cfg,clusters:[...cfg.clusters,blank()]})}><b>＋</b><span>新增 Kafka 集群</span><small>支持无认证、SASL 与 TLS</small></button></div><section className="retention"><h3>审计保留策略</h3><label>保留天数<input type="number" min="1" value={cfg.audit.retentionDays} onChange={e=>setCfg({...cfg,audit:{...cfg.audit,retentionDays:Number(e.target.value)}})}/></label><label>单文件上限 (MB)<input type="number" min="1" value={cfg.audit.maxFileSizeMB} onChange={e=>setCfg({...cfg,audit:{...cfg.audit,maxFileSizeMB:Number(e.target.value)}})}/></label></section>{backups.length>0&&<section className="backups"><h3>配置备份</h3>{backups.slice(0,10).map(backup=><div key={backup.id}><code>{backup.id}</code><span>{new Date(backup.createdAt).toLocaleString()} · {(backup.size/1024).toFixed(1)} KB</span><button className="button ghost" onClick={()=>restore(backup.id)}>回滚</button></div>)}</section>}</>
}
