import { FormEvent,useEffect,useState } from 'react';
import { api } from '../lib/api';
import { Topic,TopicConfig } from '../lib/types';
import { Dialog,Empty,ErrorNotice,Loading,PageHeader } from '../components/Common';

export function TopicsPage({clusterId}:{clusterId:string}){
 const[items,setItems]=useState<Topic[]>([]),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const[selected,setSelected]=useState<Topic>(),[creating,setCreating]=useState(false);
 const load=()=>{if(!clusterId)return;setLoading(true);api.get<{items:Topic[]}>(`/api/v1/clusters/${clusterId}/topics?search=${encodeURIComponent(search)}&pageSize=200`).then(r=>{setItems(r.items);setError('')}).catch(e=>setError(e.message)).finally(()=>setLoading(false))};
 useEffect(load,[clusterId,search]);
 const remove=async(topic:string)=>{if(prompt(`输入 Topic 名称确认删除：${topic}`)!==topic)return;await api.delete(`/api/v1/clusters/${clusterId}/topics/${encodeURIComponent(topic)}`);setSelected(undefined);load()};
 return <><PageHeader code="02 / TOPICS" title="Topic 工作台" description="检查 Leader、Replica、ISR 与运行配置，完成日常生命周期操作。" actions={<><input className="search" placeholder="搜索 Topic /" value={search} onChange={e=>setSearch(e.target.value)}/><button className="button primary" onClick={()=>setCreating(true)}>＋ 创建 Topic</button></>}/>{error&&<ErrorNotice message={error}/>} {loading?<Loading/>:items.length===0?<Empty title="没有匹配的 Topic" detail="调整搜索条件，或创建第一个 Topic。"/>:<div className="table-wrap"><table><thead><tr><th>TOPIC</th><th>PARTITIONS</th><th>RF</th><th>ISR STATUS</th><th></th></tr></thead><tbody>{items.map(topic=><tr key={topic.Name} onClick={()=>setSelected(topic)}><td><b>{topic.Name}</b>{topic.Internal&&<small className="tag">INTERNAL</small>}</td><td>{topic.PartitionCount}</td><td>{topic.ReplicationFactor}</td><td><span className={topic.UnderReplicated?'bad':'good'}>{topic.UnderReplicated?`${topic.UnderReplicated} 异常`:'HEALTHY'}</span></td><td>→</td></tr>)}</tbody></table></div>}{selected&&<TopicDetail clusterId={clusterId} topic={selected} close={()=>setSelected(undefined)} remove={()=>remove(selected.Name)} refreshed={()=>{load()}}/>}{creating&&<CreateTopic clusterId={clusterId} close={()=>setCreating(false)} saved={()=>{setCreating(false);load()}}/>}</>;
}

function TopicDetail({clusterId,topic,close,remove,refreshed}:{clusterId:string;topic:Topic;close:()=>void;remove:()=>void;refreshed:()=>void}){
 const[configs,setConfigs]=useState<TopicConfig[]>([]),[error,setError]=useState(''),[adding,setAdding]=useState(false);
 const loadConfigs=()=>api.get<{items:TopicConfig[]}>(`/api/v1/clusters/${clusterId}/topics/${encodeURIComponent(topic.Name)}/configs`).then(r=>setConfigs(r.items)).catch(e=>setError(e.message));
 useEffect(()=>{loadConfigs()},[clusterId,topic.Name]);
 async function addPartitions(e:FormEvent<HTMLFormElement>){e.preventDefault();const count=Number(new FormData(e.currentTarget).get('count'));try{await api.post(`/api/v1/clusters/${clusterId}/topics/${encodeURIComponent(topic.Name)}/partitions`,{count});setAdding(false);refreshed()}catch(reason){setError(reason instanceof Error?reason.message:'扩容失败')}}
 async function alter(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget),name=String(data.get('name')||'').trim(),raw=String(data.get('value')||'');if(!name)return;try{await api.put(`/api/v1/clusters/${clusterId}/topics/${encodeURIComponent(topic.Name)}/configs`,{configs:{[name]:raw===''?null:raw}});(e.currentTarget).reset();await loadConfigs()}catch(reason){setError(reason instanceof Error?reason.message:'配置失败')}}
 return <Dialog title={topic.Name} onClose={close}><div className="dialog-body topic-detail"><div className="detail-stats"><span>PARTITIONS<b>{topic.PartitionCount}</b></span><span>REPLICATION<b>{topic.ReplicationFactor}</b></span><span>ISR WARN<b>{topic.UnderReplicated}</b></span></div>{error&&<ErrorNotice message={error}/>}<div className="partition-grid">{topic.Partitions.map(p=><div key={p.ID}><b>P{p.ID}</b><span>LEADER {p.Leader}</span><small>ISR [{p.ISR.join(', ')}]</small></div>)}</div><div className="topic-actions"><button className="button ghost" onClick={()=>setAdding(!adding)}>＋ 增加分区</button><button className="button danger" onClick={remove}>删除 Topic</button></div>{adding&&<form className="inline-form" onSubmit={addPartitions}><input name="count" type="number" min="1" defaultValue="1"/><button className="button primary">确认扩容</button></form>}<h3>TOPIC CONFIGURATION</h3><form className="inline-form config-edit" onSubmit={alter}><input name="name" required placeholder="retention.ms"/><input name="value" placeholder="新值；留空恢复默认"/><button className="button primary">应用</button></form><div className="config-list">{configs.map(c=><div key={c.name}><code>{c.name}</code><span>{c.sensitive?'••••••':c.value??'∅'}</span><small>{c.source}</small></div>)}</div></div></Dialog>;
}

function CreateTopic({clusterId,close,saved}:{clusterId:string;close:()=>void;saved:()=>void}){const[error,setError]=useState('');async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);try{await api.post(`/api/v1/clusters/${clusterId}/topics`,{name:data.get('name'),partitions:Number(data.get('partitions')),replicationFactor:Number(data.get('replication'))});saved()}catch(reason){setError(reason instanceof Error?reason.message:'创建失败')}}return <Dialog title="创建 Topic" onClose={close}><form className="dialog-body form" onSubmit={submit}><label>名称<input name="name" required placeholder="orders.v1"/></label><div className="form-row"><label>Partitions<input name="partitions" type="number" min="1" defaultValue="3"/></label><label>Replication Factor<input name="replication" type="number" min="1" defaultValue="1"/></label></div>{error&&<ErrorNotice message={error}/>}<button className="button primary">创建并验证</button></form></Dialog>}
